name: E2E (ANDROID)
on:
  pull_request:
    branches: [main]

jobs:
  run_android_test:
    name: E2E (ANDROID)
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          # cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      # - name: Install Java JDK
      #   uses: joschi/setup-jdk@v1
      #   with:
      #     java-version: 'openjdk8'
      #     architecture: 'x64'
      #   env:
      #     # https://github.com/actions/toolkit/issues/641#issuecomment-728963957
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
